name: Final Deploy SDT
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Deploy directly
    runs-on: ubuntu-latest
    steps:
    - name: ssh and pull and restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          . init.sh
          cd /opt/software-discovery-tool-deploy
          sudo chown -R sdtuser .
          git checkout main
          git submodule foreach git pull --ff-only
          sudo cp -u -r software-discovery-tool/ ../software-discovery-tool/
          sudo chown -R apache:apache /opt/software-discovery-tool
          sudo -u apache /opt/software-discovery-tool/bin/config_build.py
          sudo apachectl restart
